name: {{package_name}}
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  freezed:
  freezed_annotation:
  flutter_riverpod:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation:

dev_dependencies:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true